Select:
( S -> LImports LRules ) = { NAME , HASHID , IMPORT , COLON , LBRACKET , ASTRISK , DOT , EF }
( LImports -> Import LImports ) = { IMPORT }
( LImports ->  ) = { NAME , HASHID , COLON , LBRACKET , ASTRISK , DOT , EF }
( Import -> IMPORT STRING SEMICOLON ) = { IMPORT }
( LRules -> Rule LRules ) = { NAME , HASHID , COLON , LBRACKET , ASTRISK , DOT }
( LRules ->  ) = { EF }
( Rule -> Selectors LBRACE LDeclaretions RBRACE ) = { NAME , HASHID , COLON , LBRACKET , ASTRISK , DOT }
( LDeclaretions -> Declaration SEMICOLON MoreDeclerations ) = { NAME }
( MoreDeclerations -> LDeclaretions ) = { NAME }
( MoreDeclerations ->  ) = { RBRACE }
( Selectors -> SimpleSelector MoreSelectors ) = { NAME , HASHID , COLON , LBRACKET , ASTRISK , DOT }
( MoreSelectors -> Selectors ) = { NAME , HASHID , COLON , LBRACKET , ASTRISK , DOT }
( MoreSelectors ->  ) = { LBRACE }
( SimpleSelector -> Astrisk SelectorModifier ) = { NAME , HASHID , COLON , LBRACKET , ASTRISK , DOT }
( Astrisk -> ASTRISK ) = { ASTRISK }
( Astrisk ->  ) = { NAME , HASHID , COLON , LBRACKET , DOT }
( SelectorModifier -> DOT NAME ) = { DOT }
( SelectorModifier -> COLON NAME ) = { COLON }
( SelectorModifier -> LBRACKET NAME EQUAL Term RBRACKET ) = { LBRACKET }
( SelectorModifier -> HASHID ) = { HASHID }
( SelectorModifier -> NAME ) = { NAME }
( Declaration -> NAME COLON LTerms Important ) = { NAME }
( Important -> IMPORTANT ) = { IMPORTANT }
( Important ->  ) = { SEMICOLON }
( LTerms -> Term MoreTerms ) = { NAME , HASHID , STRING , NUMBER , UNIT }
( MoreTerms -> LTerms ) = { NAME , HASHID , STRING , NUMBER , UNIT }
( MoreTerms ->  ) = { IMPORTANT , SEMICOLON }
( Term -> NUMBER ) = { NUMBER }
( Term -> UNIT ) = { UNIT }
( Term -> STRING ) = { STRING }
( Term -> NAME ) = { NAME }
( Term -> HASHID ) = { HASHID }

